name: Test

on:
  push:
    branches:
    - develop
    - v3
  pull_request:

jobs:
  cpp:
    name: 'C++ tests'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conan install and build
        run: |
          conan profile detect
          conan build . -s:h libqasm/*:build_type=Debug -o libqasm/*:build_tests=True -o libqasm/*:compat=True -b missing

      - name: Run tests
        run: ctest -C Debug --output-on-failure

  python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel pytest numpy
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y swig
        echo "LIBQASM_BUILD_TYPE=Debug" >> $GITHUB_ENV
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex swig
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
        echo "LIBQASM_BUILD_TYPE=Debug" >> $GITHUB_ENV
    - uses: actions/cache@v3
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-python-1
        restore-keys: |
          ${{ runner.os }}-chocolatey-python-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        choco install winflexbison3 --version 2.5.18.20190508
        #choco install swig --version 4.0.1
        echo "LIBQASM_BUILD_TYPE=Release" >> $GITHUB_ENV
    - name: Build
      env:
        NPROCS: 100
      run: python -m pip install --verbose .
    - name: Test
      run: python -m pytest

  conda:
    name: Conda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        miniconda-version: "latest"
        python-version: 3.10
        show-channel-urls: true
        use-only-tar-bz2: true
    - name: Install conda dependencies
      run: conda install conda-build conda-verify -y
    - name: Build & test
      env:
        NPROCS: 100
      run: conda build python/conda
    - name: Install
      run: conda install libqasm --use-local

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build without pushing
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: libqasm:latest
