name: Test

on:
  push:
    branches:
    - v3_1
  pull_request:

jobs:
  cpp-linux:
    name: 'C++ tests (gcc-clang/Linux/x64)'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
        compiler:
          - clang++
          - g++
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install conan
        run: python -m pip install --upgrade pip conan
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and build
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          conan profile detect
          conan build . -s:h compiler.cppstd=20 -s:h libqasm/*:build_type=${{ matrix.build_type }} -o libqasm/*:build_tests=True -o libqasm/*:compat=True -o libqasm/*:asan_enabled=True -b missing
      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

  cpp-macos:
    name: 'C++ tests (clang/MacOS/x64)'
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install conan
        run: python -m pip install --upgrade pip conan
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and build
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          conan profile detect
          conan build . -s:h compiler.cppstd=20 -s:h libqasm/*:build_type=${{ matrix.build_type }} -o libqasm/*:build_tests=True -o libqasm/*:compat=True -o libqasm/*:asan_enabled=True -b missing
      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

  cpp-windows:
    name: 'C++ tests (msvc/Windows/x64)'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - Release
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install conan
        run: python -m pip install --upgrade pip conan
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and build
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          conan profile detect
          conan build . -s:h compiler.cppstd=20 -s:h libqasm/*:build_type=${{ matrix.build_type }} -o libqasm/*:build_tests=True -o libqasm/*:compat=True -o libqasm/*:asan_enabled=True -b missing
      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

  cpp-arm64:
    name: 'C++ tests (gcc/Linux/ARM64, clang/MacOS/ARM64)'
    runs-on: [self-hosted, ARM64, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os:
          - Linux
          - macOS
    steps:
      - if: matrix.os == 'Linux'
        name: Install gcc and python (Linux)
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install gcc python3 python3-pip python3-venv
        shell: bash
      - if: matrix.os == 'macOS'
        name: Install gcc and python (MacOS)
        run: |
          brew install gcc python
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and build
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip conan
          conan build . -s:h compiler.cppstd=20 -s:h libqasm/*:build_type=Release -o libqasm/*:build_tests=True -o libqasm/*:compat=True -o libqasm/*:asan_enabled=True -b missing
      - name: Test
        working-directory: build
        run: ctest -C Release --output-on-failure

  python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip numpy pytest setuptools wheel
      - name: Install SWIG, and set build type (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y swig
          echo "LIBQASM_BUILD_TYPE=Debug" >> $GITHUB_ENV
      - name: Install flex/bison and SWIG, and set build type (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig
          echo "LIBQASM_BUILD_TYPE=Debug" >> $GITHUB_ENV
      - name: Set build type (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "LIBQASM_BUILD_TYPE=Release" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          NPROCS: 100
        run: python -m pip install --verbose .
      - name: Test
        run: python -m pytest

  conda:
    name: Conda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          miniconda-version: "latest"
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: Install conda dependencies
        run: conda install conda-build conda-verify -y
      - name: Build & test
        env:
          NPROCS: 100
        run: conda build python/conda
      - name: Install
        run: conda install libqasm --use-local

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build without pushing
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: libqasm:latest
