name: update_v3_distro

on:
  push:
    branches:
    - v3

jobs:
  v3_distro-artifact-upload:
    if: ${{ false }}
    name: 'v3_distro artifact upload'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed lexer or parser files
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: src{/v1,}/*.{l,y}
      - name: Get latest CMake
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: lukka/get-cmake@latest
      - name: Configure
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          mkdir ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          cmake .. -B .
      - name: Build C++
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/build
          cmake --build . --parallel
      - name: Build Python
        env:
          NPROCS: 100
        run: python -m pip install --verbose .
      - name: Upload artifact
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: v3_distro-artifact
          path: |
            ${{ github.workspace }}/build/_deps/tree-gen-src/include/
            ${{ github.workspace }}/build/_deps/tree-gen-src/src/tree-all.cpp
            ${{ github.workspace }}/build/include/v1/*.hpp          
            ${{ github.workspace }}/build/py_gen/v1/*.py
            ${{ github.workspace }}/build/src/cqasm-version-lexer.*
            ${{ github.workspace }}/build/src/cqasm-version-parser.*
            ${{ github.workspace }}/build/src/v1/cqasm-.*-gen.cpp
            ${{ github.workspace }}/build/src/v1/cqasm-lexer.*
            ${{ github.workspace }}/build/src/v1/cqasm-parser.*
            ${{ github.workspace }}/src/cqasm-version-lexer.l
            ${{ github.workspace }}/src/cqasm-version-parser.y
            ${{ github.workspace }}/src/v1/cqasm-lexer.l
            ${{ github.workspace }}/src/v1/cqasm-parser.y

  v3_distro-artifact-download:
    if: ${{ false }}
    name: 'v3_distro artifact download'
    runs-on: ubuntu-latest
    needs: v3_distro-artifact-upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v3_distro
          fetch-depth: 0
          ssh-key: ${{ secrets.DISTRO_DEPLOY_KEY }}
          persist-credentials: true
      - name: Download v3_distro-artifact
        id: download-v3_distro-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: v3
          name: v3_distro-artifact
          path: artifact
          workflow: v3_distro-artifact-upload.yml
          workflow_conclusion: success
      - name: Display structure of downloaded files
        run: ls -R artifact
      - name: Copy artifact files to destination
        run: |
          cp artifact/build/_deps/tree-gen-src/include/* include/tree-gen
          cp artifact/build/_deps/tree-gen-src/src/tree-all.cpp src/tree-gen
          cp artifact/build/include/v1/* include/v1
          cp artifact/build/py_gen/v1/* python/v1
          cp artifact/build/src/*.hpp include
          cp artifact/build/src/*.{cpp,txt} src
          cp artifact/build/src/v1/*.hpp include/v1
          cp artifact/build/src/v1/*.{cpp,txt} src/v1
          cp artifact/src/*.{l,y} src
          cp artifact/src/v1/*.{l,y} src/v1
      - name: Update artifact files in destination
        run: |
          python scripts/update_artifact_files.py
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git commit -a -m "Updating v3_distro with new generated files from v3"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: v3_distro
          ssh: true
