name: update_v3_distro

on:
  push:
    branches:
    - v3
  pull_request:

jobs:
  v3_distro-artifact-upload:
    name: 'v3_distro artifact upload'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed lexer or parser files
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: src{/v1,}/*.{l,y}
      - name: Get latest CMake
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: lukka/get-cmake@latest
      - name: Configure
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          mkdir ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          cmake .. -B .
      - name: Build C++
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/build
          cmake --build . --parallel
      - name: Build Python
        env:
          NPROCS: 100
        run: python -m pip install --verbose .
      - name: Upload artifact
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: v3_distro-artifact
          path: |
            ${{ github.workspace }}/build/_deps/tree-gen-src/include/
            ${{ github.workspace }}/build/_deps/tree-gen-src/src/tree-all.cpp
            ${{ github.workspace }}/build/include/v1/*.hpp          
            ${{ github.workspace }}/build/py_gen/v1/*.py
            ${{ github.workspace }}/build/src/cqasm-version-lexer.*
            ${{ github.workspace }}/build/src/cqasm-version-parser.*
            ${{ github.workspace }}/build/src/v1/cqasm-.*-gen.cpp
            ${{ github.workspace }}/build/src/v1/cqasm-lexer.*
            ${{ github.workspace }}/build/src/v1/cqasm-parser.*
            ${{ github.workspace }}/src/cqasm-version-lexer.l
            ${{ github.workspace }}/src/cqasm-version-parser.y
            ${{ github.workspace }}/src/v1/cqasm-lexer.l
            ${{ github.workspace }}/src/v1/cqasm-parser.y

  v3_distro-artifact-download:
    name: 'v3_distro artifact download'
    runs-on: ubuntu-latest
    needs: v3_distro-artifact-upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 0e471169363c5ff188cdb60edd431ea8002989b7
          path: v3_distro
          fetch-depth: 0
      - name: Download v3_distro-artifact
        id: download-v3_distro-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: v3
          name: v3_distro-artifact
          path: artifact
          workflow: v3_distro-artifact-upload.yml
          workflow_conclusion: success
      - name: Display structure of downloaded files
        run: ls -R artifact
      - name: Copy artifact files to destination
        run: |
          cp artifact/build/_deps/tree-gen-src/include/* v3_distro/include/tree-gen
          cp artifact/build/_deps/tree-gen-src/src/tree-all.cpp v3_distro/src/tree-gen
          cp artifact/build/include/v1/* v3_distro/include/v1
          cp artifact/build/py_gen/v1/* v3_distro/python/v1
          cp artifact/build/src/*.hpp v3_distro/include
          cp artifact/build/src/*.{cpp,txt} v3_distro/src
          cp artifact/build/src/v1/*.hpp v3_distro/include/v1
          cp artifact/build/src/v1/*.{cpp,txt} v3_distro/src/v1
          cp artifact/src/*.{l,y} v3_distro/src
          cp artifact/src/v1/*.{l,y} v3_distro/src/v1
#      - name: Delete artifact files
#        uses: geekyeggo/delete-artifact@v2
#        with:
#          name: v3_distro-artifact
      - name: Update artifact files in destination
        run: |
          cd v3_distro
          python scripts/update_artifact_files.py
#      - name: Get latest CMake
#        uses: lukka/get-cmake@latest
#      - name: Configure
#        run: |
#          mkdir ${{ github.workspace }}/build
#          cd ${{ github.workspace }}/build
#          cmake .. -B . -DCMAKE_BUILD_TYPE=Debug -DLIBQASM_BUILD_TESTS=ON -DLIBQASM_COMPAT=ON
#      - name: Build C++
#        run: |
#          cd ${{ github.workspace }}/build
#          cmake --build . --parallel
#      - name: Install Python dependencies
#        run: |
#          python -m pip install --upgrade pip setuptools wheel pytest numpy
#          echo "LIBQASM_BUILD_TYPE=Debug" >> $GITHUB_ENV
#      - name: Build Python
#        env:
#          NPROCS: 100
#        run: python -m pip install --verbose .
#      - name: Run C++ tests
#        run: ctest -C Debug --output-on-failure
#      - name: Run Python tests
#        run: python -m pytest
      - name: Commit files
        run: |
          cd v3_distro
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rev-parse --abbrev-ref HEAD
          git status
          git commit -a -m "Updating v3_distro with new generated files from v3"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: v3_distro
          force_with_lease: true
