name: v3_distro artifact upload

on:
  push:
    branches:
    - v3
  pull_request:

jobs:
  v3_distro-artifact-upload:
    name: 'v3_distro artifact upload'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed lexer or parser files
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: src{/v1,}/*.{l,y}
      - name: Get latest CMake
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: lukka/get-cmake@latest
      - name: Configure
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          mkdir ${{ github.workspace }}/build 
          cd ${{ github.workspace }}/build
          cmake .. -B .
      - name: Build C++
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/build
          cmake --build . --parallel
      - name: Build Python
        env:
          NPROCS: 100
        run: python -m pip install --verbose .
      - name: Upload artifact
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: v3_distro-artifact
          path: |
            ${{ github.workspace }}/build/_deps/tree-gen-src/include/
            ${{ github.workspace }}/build/_deps/tree-gen-src/src/tree-all.cpp
            ${{ github.workspace }}/build/include/v1/*.hpp          
            ${{ github.workspace }}/build/py_gen/v1/*.py
            ${{ github.workspace }}/build/src/cqasm-version-lexer.*
            ${{ github.workspace }}/build/src/cqasm-version-parser.*
            ${{ github.workspace }}/build/src/v1/cqasm-.*-gen.cpp
            ${{ github.workspace }}/build/src/v1/cqasm-lexer.*
            ${{ github.workspace }}/build/src/v1/cqasm-parser.*
            ${{ github.workspace }}/src/cqasm-version-lexer.l
            ${{ github.workspace }}/src/cqasm-version-parser.y
            ${{ github.workspace }}/src/v1/cqasm-lexer.l
            ${{ github.workspace }}/src/v1/cqasm-parser.y
